/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Id]
      ,[FirstName]
      ,[LastName]
      ,[PhoneNumber]
      ,[Email]
      ,[Skype]
      ,[LinkedIn]
      ,[Telegram]
      ,[Facebook]
      ,[GooglePlus]
      ,[PreferableMethod]
  FROM [SimpleContacts].[dbo].[Contacts]